# Generated by Django 4.0.3 on 2022-04-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамиля')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('role', models.CharField(choices=[('Вратарь', 'Keeper'), ('Защитник', 'Defender'), ('Полузащитник', 'Midfielder'), ('Нападающий', 'Forward')], max_length=50, verbose_name='Амплуа')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='commands.command', verbose_name='Команда')),
            ],
        ),
    ]
