# Generated by Django 4.0.3 on 2022-04-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_player_is_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(default=False, verbose_name='Капитан'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Вратарь', 'Вратарь'), ('Защитник', 'Защитник'), ('Полузащитник', 'Полузащитник'), ('Нападающий', 'Нападающий')], max_length=50, verbose_name='Амплуа'),
        ),
    ]
