# Generated by Django 4.0.2 on 2022-05-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_alter_command_name_alter_player_is_captain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='command_photo',
            field=models.ImageField(blank=True, upload_to='img/commands/photo'),
        ),
        migrations.AddField(
            model_name='command',
            name='logo',
            field=models.ImageField(blank=True, upload_to='img/commands/logo'),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/players', verbose_name='Фото'),
        ),
    ]
