# Generated by Django 4.0.2 on 2022-05-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0004_command_command_photo_command_logo_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_photo',
            field=models.ImageField(blank=True, upload_to='commands/photo/', verbose_name='командное фото'),
        ),
        migrations.AlterField(
            model_name='command',
            name='logo',
            field=models.ImageField(blank=True, upload_to='commands/logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, upload_to='player/', verbose_name='Фото'),
        ),
    ]
