# Generated by Django 4.0.2 on 2022-05-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0006_alter_command_command_photo_alter_command_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_photo',
            field=models.ImageField(default='static/images/command.jpg', upload_to='commands/photo/', verbose_name='командное фото'),
        ),
        migrations.AlterField(
            model_name='command',
            name='logo',
            field=models.ImageField(default='static/images/logotip.jpg', upload_to='commands/logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='static/images/player.jpg', upload_to='player/', verbose_name='Фото'),
        ),
    ]
