# Generated by Django 4.0.2 on 2022-05-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0011_alter_command_command_photo_alter_command_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_photo',
            field=models.ImageField(blank=True, upload_to='commands/photo/', verbose_name='командное фото'),
        ),
        migrations.AlterField(
            model_name='command',
            name='logo',
            field=models.ImageField(blank=True, upload_to='commands/logo/', verbose_name='Логотип'),
        ),
    ]
