# Generated by Django 4.0.2 on 2022-05-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0004_command_command_photo_command_logo_player_photo'),
        ('tournaments', '0003_match_status_alter_event_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='commands',
            field=models.ManyToManyField(related_name='tournaments', to='commands.Command'),
        ),
    ]
