# Generated by Django 4.0.2 on 2022-05-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_tournament_commands'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='background',
            field=models.ImageField(blank=True, upload_to='tournament', verbose_name='Фон турнира'),
        ),
    ]
