# Generated by Django 4.0.2 on 2022-06-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о турнире'),
        ),
    ]
