# Generated by Django 4.0.2 on 2022-07-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_alter_match_tournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date_and_time']},
        ),
    ]
