# Generated by Django 4.0.3 on 2022-04-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('goals', models.IntegerField(default=0, verbose_name='Голы')),
                ('cards', models.IntegerField(default=0, verbose_name='Карточки')),
            ],
        ),
    ]
